### ISSUE TITLE
Intégrer l'utilisation d'un certificat présent sur le client #8

### ISSUE THREAD

**Issue by julien2512** [openeventdatabase/frontend#2]
Recopie de #8 du backend : https://github.com/openeventdatabase/backend/issues/8

Actuellement, le certificat privé est à saisir dans la page du navigateur ! Il est donc lisible dans le DOM. Attention aux attaques XSS, et ce n'est pas non plus très pratique pour l'utilisateur.

La signature devrait nécessiter systématiquement la saisie d'un code PIN pour deverrouiller l'accès à la clé privée ...

A étudier donc l'intégration avec des parapheurs existants (il en existe chez adullact notamment).

Une piste :
http://fr.worldline.com/fr-fr/home/solutions/services-mobiles-et-transactionnels/worldline-signer/worldline-signer-server.html
Une autre :
http://www.ssi.gouv.fr/agence/publication/publication-des-specifications-techniques-en-matiere-didentification-electronique-eidas/
Une troisième :
https://github.com/OpenSC/OpenSC/wiki/Using-smart-cards-with-Java-SE

Middleware opensource pour utiliser IAS ECC , apparemment y compris en javascript. Source : estonie !

@rr8779 est en cours de test de la signature avec LibreOffice. L'impact client et serveur reste à POCer.
voir https://github.com/rr8779/odt_extract

J'ai bien testé l'utilisation de window.crypto.signText, mais l'implémentation des versions antérieures à Firefox 34 n'est pas conforme avec les derniers standards IAS-ECC.
De fait, l'implémentation de window.crypto.signText a simplement été retiré de firefox ... En attente de réimplémentation. Un plugin rétablissant le fonctionnement a été proposé par la communauté, mais pas conforme non plus.

L'implémentation proposée par firefox a toutefois été soumise au W3C :
http://www.w3.org/2012/webcrypto/WebCryptoAPI/
en attente de validation. Avec un peu de chance, cela sera natif dans quelques mois, mais le protocole IAS-ECC évolue aussi de son coté ...

Facile à tester :

```
<script>
  alert(window.crypto.signText("test","ask"));
</script>

```

Firefox 45 : ko, n'est plus implémenté. Plugin pas conforme IAS-ECC
Firefox 38 : ko, n'est plus implémenté. Plugin pas conforme IAS-ECC
Firefox 31 : ko, pas conforme IAS-ECC
Firefox 24 : ko, pas conforme IAS-ECC

En attendant, il ne reste qu'à mettre en place une applet, il y en a plusieurs à tester.

**Comment by julien2512** [comment]
En attendant les tests d'applet / java web start, je vais proposer un pull request qui utilise signText, uniquement s'il est présent dans le navigateur utilisé.

**Comment by Morendil** [comment]
Mes recherches sur la compatibilité "théorique" entre JWT et WebCrypto ne sont pas concluantes. Je ne peux pas affirmer qu'il existe un algorithme asymétrique proposé par les deux API.

Au-delà, il me semble que la question d'autoriser l'accès aux certificats stockés localement dans le navigateur ne fait l'objet d'aucune proposition crédible de standardisation à l'heure actuelle. La spécification draft WebCrypto fait l'impasse là-dessus, c'est peut-être ce qu'il faut comprendre aussi de la position de Mozilla pour justifier le retrait de signText.

Je n'ai pas de bons résultats sur mes premiers tests, sur FireFox 44 après installation du plugin signTextJs. J'ai créé une CA et importé un certificat client, en choisissant ce certificat le résultat de  `window.crypto.signText("foo","ask")` est `"error:internalError"`

Je ne peux pas vraiment évaluer la compatibilité des algorithmes utilisés par l'API signText, sans voir le résultat produit. Julien, peux-tu faire fonctionner en local la variante avec signText? Si oui, peux-tu m'envoyer le message résultant?

Julien, ce point est-il bloquant pour les jalons "exercice/expérimentation" et "mise en prod de l'appli Vélib"? Dans l'affirmative, pourrait-on détailler le scénario plausible d'une attaque XSS visant à extraire la clé privée, pour voir si on trouve d'autres moyens de s'en prémunir?

Par exemple on peut envisager d'utiliser l'API FileReader plutôt qu'une textarea (la clé est alors dans la mémoire JS et plus dans le DOM), pour accéder à une clé stockée dans un fichier texte, éventuellement sur un module matériel (clé USB sécurisée?).

**Comment by julien2512** [comment]
Bien sur cela fonctionne de mon côté ! La chaîne de certification de ton
certificat est elle présente dans ton navigateur (j'ai testé avec un auto-signé, cela ne marche pas) ? Il faut aussi disposer
d'un mot de passe principal dans firefox (celui qui sécurise les
certificats et mots de passe).

J'ai rapporté l'issue correspondante (Error message are not easy to understand #42) :
https://github.com/mozkeeler/signTextJS/issues/42

Ce scénario reste le plus proche de notre cible, et avec zéro maintenance coté front.
Je dois encore poser la question à Adullact sur d'autres projets: ils ont à priori le même souci que nous.

Mais je jette tout de même un coup d'oeil aux fonctions de crypto de mozilla et de signtext :
https://dxr.mozilla.org/mozilla-central/source/security/nss/lib/pkcs7/p7create.c?q=%2Bfunction%3A%22sec_pkcs7_add_signer%28SEC_PKCS7ContentInfo+%2A%2C+CERTCertificate+%2A%2C+SECCertUsage%2C+CERTCertDBHandle+%2A%2C+SECOidTag%2C+SECItem+%2A%29%22&redirect_type=single#150
!
pour trouver l'algorithme commun avec ton API ...

**Comment by julien2512** [comment]
A priori, les algos disponibles dans nss :

```
  SEC_OID_PKCS1_MD5_WITH_RSA_ENCRYPTION
  SEC_OID_PKCS1_SHA1_WITH_RSA_ENCRYPTION
  SEC_OID_ISO_SHA_WITH_RSA_SIGNATURE
  SEC_OID_ISO_SHA1_WITH_RSA_SIGNATURE
  SEC_OID_ANSIX9_DSA_SIGNATURE_WITH_SHA1_DIGEST
  SEC_OID_BOGUS_DSA_SIGNATURE_WITH_SHA1_DIGEST
  SEC_OID_ANSIX962_ECDSA_SHA1_SIGNATURE
  SEC_OID_MISSI_DSS
  SEC_OID_MISSI_KEA_DSS
  SEC_OID_MISSI_KEA_DSS_OLD
  SEC_OID_MISSI_DSS_OLD
  SEC_OID_ANSIX962_ECDSA_SHA224_SIGNATURE
  SEC_OID_PKCS1_SHA224_WITH_RSA_ENCRYPTION
  SEC_OID_NIST_DSA_SIGNATURE_WITH_SHA224_DIGEST
  SEC_OID_ANSIX962_ECDSA_SHA256_SIGNATURE
  SEC_OID_PKCS1_SHA256_WITH_RSA_ENCRYPTION
  SEC_OID_NIST_DSA_SIGNATURE_WITH_SHA256_DIGEST
  SEC_OID_ANSIX962_ECDSA_SHA384_SIGNATURE
  SEC_OID_PKCS1_SHA384_WITH_RSA_ENCRYPTION
  SEC_OID_ANSIX962_ECDSA_SHA512_SIGNATURE
  SEC_OID_PKCS1_SHA512_WITH_RSA_ENCRYPTION
```

source : https://chromium.googlesource.com/external/webrtc/+/1b794d56b72853fe2eecbea2c719886c44578ed8/webrtc/base/nssidentity.cc

ou plus officiellement ici :
http://www-archive.mozilla.org/projects/security/pki/jss/javadoc/org/mozilla/jss/crypto/Algorithm.html

Soit 
SEC_OID_PKCS1_SHA256_WITH_RSA_ENCRYPTION = 41
(source : http://www-archive.mozilla.org/projects/security/pki/jss/javadoc/constant-values.html#org.mozilla.jss.crypto.Algorithm.SEC_OID_PKCS1_SHA384_WITH_RSA_ENCRYPTION)

**Comment by julien2512** [comment]
J'ai proposé l'amélioration de signTextJS :
https://github.com/mozkeeler/signTextJS/issues/43
Mais je n'ai pas encore eu le temps de tester ma version :
https://github.com/julien2512/signTextJS
Peut-être en fin de semaine.
(attention, elle n'est pas signée par mozilla, il faut xpinstall.signatures.required=false dans about:config).

@Morendil il faudrait que tu sois plus précis sur l'algorithme employé avec JWS: 
Dans 
`var sJWT = KJUR.jws.JWS.sign(oHeader.alg, sHeader, sPayload, prvKey);`
l'algorithme est RS256.
Qu'est-ce que cela veut dire exactement ? Ce n'est pas mentionné dans le source de JWS.

**Comment by Morendil** [comment]
D'après la spec, RS256 correspond à "RSASSA-PKCS1-v1_5 with the SHA-256 hash algorithm": https://tools.ietf.org/html/rfc7519

**Comment by julien2512** [comment]
J'ai retrouvé une trace chez mozilla
https://hg.mozilla.org/mozilla-central/rev/3efccd28317b
`#define WEBCRYPTO_ALG_RSASSA_PKCS1  "RSASSA-PKCS1-v1_5"`

Mais une définition complète de ton algorithme est ici :
https://tools.ietf.org/html/rfc3447#section-8.2

Je cherche la correspondance exacte ...

**Comment by julien2512** [comment]
OK, ta librairie est spécialisée dans PKCS1 (signature RSA RFC 3447), pour le moment la mienne dans PKCS7 (adapté aux pki - RFC 2315) !

Je vais continuer à creuser pour voir comment adapter signText pour utiliser les librairies Pkcs1 de mozilla. (c'est toujours bon à savoir).

Autre chose, tes certificats sont générés avec openssl ?

**Comment by rr8779** [comment]
Apparement ce fork est plus actif https://github.com/jasp00/signTextJS (et également dispo sur addons.mozilla.org)

**Comment by julien2512** [comment]
@rr8779 mais toujours moins que le mien (lol) !
Mais la mécanique github fait que le dépot principal est forké à la place ! Je mettrai à jour le mien avec. Je vais leur proposer mon pull request et issue.

**Comment by Morendil** [comment]
Oui `openssl x509` etc (je n'ai plus la commande exacte en tête)

Les PKCSxx c'est encore un peu la jungle pour moi, ce sont des documents normatifs qui ne recouvrent pas les mêmes périmètres. Le PKCS1 c'est des primitives de crypto si j'ai bien compris, le format généré par openssl est du "X509 encodé PEM" et je crois que c'est ça que la lib JWT ingère. Par ailleurs la lib JWT prend en charge des opérations comme le formatage canonique du JSON et le format tripartite {header,payload,signature}, qui seraient à réimplémenter (?) sur la base de signText.
