### ISSUE TITLE
Disposer d'un certificat HTTPS

### ISSUE THREAD

**Issue by julien2512** [openeventdatabase/frontend#3]
Actuellement, un proxy est présent pour accéder au backend. L'accès en HTTPS n'est donc pas effectif depuis le navigateur.

**Comment by Morendil** [comment]
L'accès au frontal d'édition est désormais sécurisé par un certificat LetsEncrypt. Les requêtes pour l'API passent toujours par un proxy sur alerte.oedb.org, mais sont bien faites en HTTPS.
